
-- MySQL Script generated by MySQL Workbench
-- Fri Oct 25 21:27:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema barbercenter
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema barbercenter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `barbercenter` DEFAULT CHARACTER SET utf8 ;
USE `barbercenter` ;

-- -----------------------------------------------------
-- Table `barbercenter`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Cliente` (
  `CPF` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`CPF`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`Barbearia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Barbearia` (
  `cnpj` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `telefone` VARCHAR(45) NULL,
  `pessoaResponsavel` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`cnpj`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Endereco` (
  `cep` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `complemento` VARCHAR(45) NULL,
  `Cliente_CPF` INT NOT NULL,
  `Barbearia_cnpj` INT NOT NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`cep`, `Barbearia_cnpj`),
  INDEX `fk_Endereco_Cliente_idx` (`Cliente_CPF` ASC) VISIBLE,
  INDEX `fk_Endereco_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Endereco_Cliente`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Endereco_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`produto` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `quantidade` INT NULL,
  `valor` DECIMAL NULL,
  `Barbearia_cnpj` INT NOT NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_produto_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`servicos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  `valor` DECIMAL NULL,
  `Barbearia_cnpj` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servicos_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_servicos_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`agendamento` (
  `id` INT NOT NULL,
  `cpf_cliente` VARCHAR(45) NOT NULL,
  `cnpj_barbearia` VARCHAR(45) NOT NULL,
  `id_servico` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `status` INT NOT NULL,
  `Cliente_CPF` INT NOT NULL,
  `Barbearia_cnpj` INT NOT NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_agendamento_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  INDEX `fk_agendamento_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_agendamento_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_agendamento_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`forma_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`forma_pagamento` (
  `id` INT NOT NULL,
  `credito` INT NULL,
  `debito` INT NULL,
  `dinheiro` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`pagamento` (
  `id` INT NOT NULL,
  `cpf_cliente` VARCHAR(45) NULL,
  `cnpj_barbearia` VARCHAR(45) NULL,
  `id_servico` VARCHAR(45) NULL,
  `id_produto` VARCHAR(45) NULL,
  `date` DATE NULL,
  `forma_pagamento` VARCHAR(45) NULL,
  `version` DATE NULL,
  `Cliente_CPF` INT NOT NULL,
  `forma_pagamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pagamento_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  INDEX `fk_pagamento_forma_pagamento1_idx` (`forma_pagamento_id` ASC) VISIBLE,
  CONSTRAINT `fk_pagamento_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pagamento_forma_pagamento1`
    FOREIGN KEY (`forma_pagamento_id`)
    REFERENCES `mydb`.`forma_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`Barbeiro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Barbeiro` (
  `Id` INT NOT NULL,
  `Nome` VARCHAR(45) NULL,
  `horario` DATETIME NULL,
  `Barbearia_cnpj` INT NOT NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`Id`),
  INDEX `fk_Barbeiro_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Barbeiro_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`Imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Imagem` (
  `img` BIT(50) NOT NULL,
  `id` INT NOT NULL,
  `Barbearia_cnpj` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Imagem_Barbearia1_idx` (`Barbearia_cnpj` ASC) VISIBLE,
  CONSTRAINT `fk_Imagem_Barbearia1`
    FOREIGN KEY (`Barbearia_cnpj`)
    REFERENCES `mydb`.`Barbearia` (`cnpj`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `barbercenter`.`Carrinho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `barbercenter`.`Carrinho` (
  `Cliente_CPF` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `Version` DATETIME NULL,
  PRIMARY KEY (`Cliente_CPF`, `produto_id`),
  INDEX `fk_Cliente_has_produto_produto1_idx` (`produto_id` ASC) VISIBLE,
  INDEX `fk_Cliente_has_produto_Cliente1_idx` (`Cliente_CPF` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_has_produto_Cliente1`
    FOREIGN KEY (`Cliente_CPF`)
    REFERENCES `mydb`.`Cliente` (`CPF`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
